### ISSUE TITLE
Login/logout

### ISSUE THREAD

**Issue by vinarius** [jc190/bookclub#3]
Login link at the top right should change to a 'Logout' link after user is authenticated.

**Comment by jimcalhoun** [comment]
How do you want to tackle this? I'm thinking we could a) create separate html pages to serve when authenticated, or b) create a script to call the API for user information on page load and if there's a user, use JavaScript to change the nav menu. Another option is to use the pug templates.

**Comment by vinarius** [comment]
I would say let's change our html to display our features for an authenticated user and only have 'sign up' / 'login' links on the navbar show on the login page. On the authenticated user's page we can have our logout element fire the logout function from passport.

Passport exposes a logout() function on req (also aliased as logOut()) that can be called from any route handler which needs to terminate a login session. Invoking logout() will remove the req.user property and clear the login session (if any).

app.get('/logout', function(req, res){
  req.logout();
  res.redirect('/');
});

http://passportjs.org/docs
